local util = require("util")

-- All sprites are generated by tools/gen_commie_doge.py as sheets laid out
-- rows = directions (index 0 = North, clockwise), columns = frames, so
-- line_length = frame_count. Frame size is 72x92, drawn at scale 0.5.
-- Each visible state is up to four co-registered layers, named from one base
-- (e.g. "idle"):
--   <base>.png         body, untinted (includes the green pistol and, in the
--                      mining state, the gold hammer & sickle tool)
--   <base>_mask.png    chest + cap fill, apply_runtime_tint -> the player's color
--   <base>_emblem.png  gold star + hammer & sickle, drawn ON TOP so the insignia
--                      stays gold over the player-colored cap
--   <base>_shadow.png  flat-black projected silhouette, draw_as_shadow -> the engine
--                      renders it translucent and time-of-day tinted

local FRAME_W, FRAME_H = 72, 92
local SCALE = 0.5
local SHIFT = util.by_pixel(0, -17)   -- lift so the paws sit on the entity origin

-- One sheet -> a RotatedAnimation layer. opts.tint marks the player-color mask layer;
-- opts.shadow marks the draw_as_shadow silhouette. The shadow shares the body's frame
-- size and shift -- the cast is baked into the pixels -- so it can never drift out of
-- alignment with the dog.
local function layer(file, frames, dirs, speed, opts)
  opts = opts or {}
  return
  {
    filename = "__commie-doge__/graphics/" .. file,
    width = FRAME_W,
    height = FRAME_H,
    frame_count = frames,
    line_length = frames,
    direction_count = dirs,
    animation_speed = speed,
    run_mode = "forward",
    apply_runtime_tint = opts.tint or nil,
    draw_as_shadow = opts.shadow or nil,
    scale = SCALE,
    shift = SHIFT,
    usage = "player",
  }
end

-- body + tint-mask + gold emblem + cast shadow, derived from one base name.
local function state(base, frames, dirs, speed)
  return { layers = {
    layer(base .. ".png",        frames, dirs, speed, {}),
    layer(base .. "_mask.png",   frames, dirs, speed, { tint = true }),
    layer(base .. "_emblem.png", frames, dirs, speed, {}),
    layer(base .. "_shadow.png", frames, dirs, speed, { shadow = true }),
  } }
end

local character = data.raw.character.character

-- A single animations entry with no `armors` key = catch-all, so every armor state
-- renders as the dog (power armor included -- all the same character). The 8-direction
-- states (index 0 = N, clockwise) face their heading. running_with_gun is 18-direction:
-- its rows sweep the gun aim N -> E -> S over the east hemisphere and the engine mirrors
-- them for the west half (matching the vanilla level1_running_gun row order, so the dog
-- aims where it shoots instead of the old frozen front pose). Because the body is mirrored
-- for west aim, its cast shadow needs a hand-made flipped companion, wired through the
-- dedicated flipped_shadow_running_with_gun field exactly as the base game does.
character.animations =
{
  {
    idle             = state("idle",    4,  8, 0.08),
    idle_with_gun    = state("idlegun", 4,  8, 0.08),
    running          = state("run",     8,  8, 0.60),
    mining_with_tool = state("mine",    6,  8, 0.40),
    running_with_gun = state("rungun",  8, 18, 0.60),
    flipped_shadow_running_with_gun =
    {
      layers = { layer("rungun_shadow_flipped.png", 8, 18, 0.60, { shadow = true }) }
    },
  }
}
