local util = require("util")

-- All sprites are generated by tools/gen_commie_doge.py as sheets laid out
-- rows = directions (index 0 = North, clockwise), columns = frames, so
-- line_length = frame_count. Frame size is 72x92, drawn at scale 0.5.
-- Three layers per state: the body (untinted; includes the green water pistol),
-- a chest+cap `apply_runtime_tint` mask layer that takes the player's chosen
-- color, and a top emblem layer with the fixed gold star + hammer & sickle (never
-- tinted, so the insignia stays gold over the player-colored cap).

local FRAME_W, FRAME_H = 72, 92
local SCALE = 0.5
local SHIFT = util.by_pixel(0, -17)   -- lift so the paws sit on the entity origin

-- One body/mask sheet -> a RotatedAnimation layer.
local function layer(file, frames, dirs, speed, tint)
  return
  {
    filename = "__commie-doge__/graphics/" .. file,
    width = FRAME_W,
    height = FRAME_H,
    frame_count = frames,
    line_length = frames,
    direction_count = dirs,
    animation_speed = speed,
    run_mode = "forward",
    apply_runtime_tint = tint or nil,
    scale = SCALE,
    shift = SHIFT,
    usage = "player",
  }
end

-- body + chest/cap tint-mask + gold emblem, as the layered animation for one state.
local function state(body, mask, emblem, frames, dirs, speed)
  return { layers = { layer(body,   frames, dirs, speed, false),
                      layer(mask,   frames, dirs, speed, true),
                      layer(emblem, frames, dirs, speed, false) } }
end

local character = data.raw.character.character

-- A single animations entry with no `armors` key = catch-all, so every armor
-- state renders as the dog. running/idle/mining/idle_with_gun are 8-direction
-- (index 0 = N, clockwise) so the dog faces its heading. running_with_gun
-- requires 18 directions; its mapping (gun-aim x movement) is undocumented and
-- buggy even in vanilla, so we tile a single front-facing pistol pose across all
-- 18 -- never directional there, but never visibly broken either. The aiming
-- pistol showcase lives in idle_with_gun, whose 8-dir mapping is correct.
character.animations =
{
  {
    idle             = state("idle.png",    "idle_mask.png",    "idle_emblem.png",    4,  8, 0.08),
    idle_with_gun    = state("idlegun.png", "idlegun_mask.png", "idlegun_emblem.png", 4,  8, 0.08),
    running          = state("run.png",     "run_mask.png",     "run_emblem.png",     8,  8, 0.60),
    mining_with_tool = state("mine.png",    "mine_mask.png",    "mine_emblem.png",    6,  8, 0.40),
    running_with_gun = state("rungun.png",  "rungun_mask.png",  "rungun_emblem.png",  8, 18, 0.60),
  }
}
